/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetoaula;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import projetoaula.Model.projeto;
import projetoaula.Model.usuario;
import projetoaula.Persistencia.JDBCprojeto;
import projetoaula.Persistencia.JDBCusuario;
import projetoaula.Persistencia.conexao;

/**
 *
 * @author thiag
 */
public class FrmRelProj extends javax.swing.JFrame {

    /**
     * Creates new form FrmRelProj
     */
    public FrmRelProj() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProjects = new javax.swing.JList<>();
        txtUserPesq = new javax.swing.JTextField();
        txtNomeProjPesq = new javax.swing.JTextField();
        txtIdProject = new javax.swing.JTextField();
        btnPesq = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Relatório Projetos");

        jScrollPane1.setViewportView(listProjects);

        txtUserPesq.setText("Pesquisar usuário");
        txtUserPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserPesqActionPerformed(evt);
            }
        });

        txtNomeProjPesq.setText("Pesquisar nome do projeto");

        txtIdProject.setText("Pesquisar ID projeto");

        btnPesq.setText("Pesquisar");
        btnPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqActionPerformed(evt);
            }
        });

        jButton1.setText("voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(425, 425, 425))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtUserPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                                .addComponent(txtNomeProjPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 135, 135)
                                .addComponent(txtIdProject, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(145, 145, 145)
                                .addComponent(btnPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesq, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeProjPesq)
                            .addComponent(txtUserPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtIdProject, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqActionPerformed
        // TODO add your handling code here:

        DefaultListModel model = new DefaultListModel();

        if (!txtUserPesq.getText().contains("Pesquisar usuário")) {
            System.out.println("Entrou no usuario");
            conexao connect = new conexao();
            JDBCusuario bd = new JDBCusuario(connect.abrirConexao());
            ArrayList<usuario> userList = bd.buscarUsuarioPorNome(txtUserPesq.getText());
            usuario user = userList.get(0);

            int idUser = user.getIdUsuario();

            JDBCprojeto bdProject = new JDBCprojeto(connect.abrirConexao());

            ArrayList<projeto> projectList = bdProject.buscarProjetosResponsavel(idUser);

            connect.fecharConexao();

            for (int i = 0; i < projectList.size(); i++) {
                projeto project = projectList.get(i);
                model.addElement("ID: " + project.getIdProjeto() + " | Nome Projeto:  " + project.getNomeProjeto() + "| Descrição: " + project.getDescProjeto() + "| Usuario Responsável: " + user.getNomeCompleto());
                model.addElement("");
            }

        }
        
        if (!txtNomeProjPesq.getText().contains("Pesquisar nome do projeto")) {
            conexao connect = new conexao();

            JDBCprojeto bdProject = new JDBCprojeto(connect.abrirConexao());

            System.out.println("Passou aqui");

            ArrayList<projeto> projectList = bdProject.buscarProjetosPorNome(txtNomeProjPesq.getText());

            connect.fecharConexao();

            System.out.println(projectList.size());

            if (projectList.size() > 0) {
                for (int i = 0; i < projectList.size(); i++) {
                    projeto project = projectList.get(i);
                    model.addElement("ID: " + project.getIdProjeto() + " | Nome Projeto:  " + project.getNomeProjeto() + "| Descrição: " + project.getDescProjeto() + "| Usuario Responsável: " + project.getNomeUser());
                    model.addElement("");
                }
            } else {
                model.addElement("Sem Resultado");
            }

        }
        
        if (!txtIdProject.getText().contains("Pesquisar ID projeto")) {
            conexao connect = new conexao();

            JDBCprojeto bdProject = new JDBCprojeto(connect.abrirConexao());

            System.out.println("Passou aqui");

            ArrayList<projeto> projectList = bdProject.buscarProjetoRelatorio(Integer.parseInt(txtIdProject.getText()));

            connect.fecharConexao();

            System.out.println(projectList.size());

            if (projectList.size() > 0) {
                for (int i = 0; i < projectList.size(); i++) {
                    projeto project = projectList.get(i);
                    model.addElement("ID: " + project.getIdProjeto() + " | Nome Projeto:  " + project.getNomeProjeto() + "| Descrição: " + project.getDescProjeto() + "| Usuario Responsável: " + project.getNomeUser());
                    model.addElement("");
                }
            } else {
                model.addElement("Sem Resultado");
            }

        }

        listProjects.setModel(model);
    }//GEN-LAST:event_btnPesqActionPerformed

    private void txtUserPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserPesqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserPesqActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrmRelatorios relatorios = new FrmRelatorios();
        relatorios.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRelProj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRelProj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRelProj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRelProj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRelProj().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesq;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listProjects;
    private javax.swing.JTextField txtIdProject;
    private javax.swing.JTextField txtNomeProjPesq;
    private javax.swing.JTextField txtUserPesq;
    // End of variables declaration//GEN-END:variables
}
